### ISSUE TITLE
[Идея] Добавить возможность изменять имя файла

### ISSUE THREAD

**Issue by BlitGaming** [Infqq/simpledemotivators#19]
Возможность изменения имени файла в методах Demotivator.create() и Quote.get() может потребоваться, например если необходимо сделать сохранение сгенерированных картинок, создание каталога с историей демотиваторов/цитат по дате/с рандомной генерацией имени.

**Comment by Infqq** [comment]
Так есть же RESULT_FILENAME='Имя файла,jpg'

**Comment by Ron788** [comment]
> Так есть же RESULT_FILENAME='Имя файла,jpg'

Не только ".jpg"

**Comment by Ron788** [comment]
В обоих методах есть параметр "RESULT_FILENAME" принимающий название выходного файла
