### ISSUE TITLE
Проблема с отображением эмоджи

### ISSUE THREAD

**Issue by BlitGaming** [Infqq/simpledemotivators#30]
Мой код:
```python
from simpledemotivators import Quote

quote = Quote("Каво? 😂", "BlitGaming")
quote.create("https://cdn.discordapp.com/avatars/413895359069159444/4532680da222a943764c5edb5a0106e7.webp?size=128",
             use_url=True)

```
![qresult](https://user-images.githubusercontent.com/79034202/139646020-a84765d7-a828-47b0-9cb8-3e92b4effab2.png)

**Comment by Infqq** [comment]
Проблема в шрифте, не поддерживает эмоджи

**Comment by BlitGaming** [comment]
> 
> 
> Проблема в шрифте, не поддерживает эмоджи

Тогда нужно изменить шрифты по умолчанию, чтобы поддерживали эмоджи

**Comment by Infqq** [comment]
Если такие есть, то я с радостью изменю

**Comment by BlitGaming** [comment]
> 
> 
> Если такие есть, то я с радостью изменю

Не закрывай тогда тему, если найдёшь шрифты, то закроешь

**Comment by Ron788** [comment]
Вина в этой проблеме (по видимому) не в шрифтах, а в pillow

> https://github.com/python-pillow/Pillow/issues/1774#issuecomment-330820569

И получается такой проблемы нет только на Ubuntu

**Comment by BlitGaming** [comment]
> 
> 
> Вина в этой проблеме (по видимому) не в шрифтах, а в pillow
> 
> > [python-pillow/Pillow#1774 (comment)](https://github.com/python-pillow/Pillow/issues/1774#issuecomment-330820569)
> 
> И получается такой проблема только на Windows

Это печально. Но по идее при написании тех же ботов, когда они будут залиты на сервер. проблем в итоге быть не должно.

**Comment by Infqq** [comment]
> Вина в этой проблеме (по видимому) не в шрифтах, а в pillow
> 
> > [python-pillow/Pillow#1774 (comment)](https://github.com/python-pillow/Pillow/issues/1774#issuecomment-330820569)
> 
> И получается такой проблема только на Windows

Я устанавливал шрифт, который поддерживает эмоджи, все работало даже на винде. А обычные шрифты и на линуксе не работают.
