### ISSUE TITLE
Ошибка в вотемарках

### ISSUE THREAD

**Issue by poma0102** [Infqq/simpledemotivators#32]
Появляется ошибка в вотемарках:

`idraw.watermark((1000 - len(watermark) * 5, 817, 1008 + len(watermark) * 5, 817), fill=0, width=4)
AttributeError: 'ImageDraw' object has no attribute 'watermark'`

**Comment by Infqq** [comment]
Исправлю в течении 20-ти минут.

**Comment by poma0102** [comment]
А почему нельзя использовать фото в байтах?
`file = await bot.download_file_by_id(message.reply_to_message.photo[-1].file_id)
    img = Image.open(file)
    print(img)
    demotivator = Demotivator('хуй', 'что?')
    demotivator.create(img, fill_color='black', font_name='arialbd.ttf', arrange=True)`

**Comment by Infqq** [comment]
Баг исправлен, обновитесь из репозитория Github: 
`pip3 install https://github.com/Infqq/simpledemotivators/archive/main.zip --upgrade`

**Comment by Infqq** [comment]
> А почему нельзя использовать фото в байтах? `file = await bot.download_file_by_id(message.reply_to_message.photo[-1].file_id)
> 
> ```
> img = Image.open(file)
> 
> print(img)
> demotivator = Demotivator('ага', 'что?')
> 
> demotivator.create(img, fill_color='black', font_name='arialbd.ttf', arrange=True)`
> ```

Постараемся добавить данную функцию в следующем обновлении, пока что нельзя.

**Comment by poma0102** [comment]
Хорошо спасибо большое)

А когда данное обновление будет ?
Если ли примерная дата?

**Comment by Infqq** [comment]
> Хорошо спасибо большое)
> 
> А когда данное обновление будет ? Если ли примерная дата?

Отпишите мне в телеграм - t.me/infjq
Разберемся, постараюсь добавить функцию в ближайшие дни.

**Comment by BlitDev** [comment]
> Хорошо спасибо большое)
> 
> А когда данное обновление будет ? Если ли примерная дата?

Это не будет добавлено, всё надо делать руками в своём коде. Если очень сильно нужно, создайте другое issue.
