### ISSUE TITLE
Легенда

### ISSUE THREAD

**Issue by moonbrawl** [Infqq/simpledemotivators#36]
Легендарнее некуда, это лучшая библиотека всех времён, позволь мне подарить эти цветы в честь тебя!
![image](https://user-images.githubusercontent.com/100240269/160651677-a63d65a4-33f8-43b2-9417-30d8818a41cc.png)

**Comment by Infqq** [comment]
Бравл старс это хорошо

**Comment by Ron788** [comment]
> Осталось только переписать всё на C#

А зачем?

**Comment by BlitDev** [comment]
> > Осталось только переписать всё на C#
> 
> А зачем?

C# быстрее, боты на нём быстрее :)

**Comment by Ron788** [comment]
> C# быстрее, боты на нём быстрее :)

Ненадо мне рассказывать что-либо про с#, я и так все знаю. Но ботов на нем писать не лучшая идея, тогда уж JS намного лучше будет.
