### ISSUE TITLE
Изменить QUOTES

### ISSUE THREAD

**Issue by l1v0n1** [Infqq/simpledemotivators#4]
Предлагаю, добавить возможность редактировать файл сохранения, а именно ("qresult.jpg") во избежание багов
Так же предлагаю добавить надпись: Цитаты великих людей , вверху цитаты.

**Comment by Infqq** [comment]
Закрою, когда сделаю

**Comment by Infqq** [comment]
Я ленивый человек.

**Comment by Infqq** [comment]
Добавил изменение названия файла в цитатах, другое позже сделаю, закрыто!
