### ISSUE TITLE
Начал использовать  данную библиотеку в Кали Линукс .Но выводит  ошибку

### ISSUE THREAD

**Issue by BUTERBROT1** [Infqq/simpledemotivators#42]
File "/home/pc/Documents/5.py", line 9, in <module>
    from simpledemotivators import Demotivator
ModuleNotFoundError: No module named 'simpledemotivators'
Устанавливал через pip3

**Comment by Infqq** [comment]
Через pip тоже не работает?

**Comment by BUTERBROT1** [comment]
При любой возможной установке вот такая ошибка

 pip3  install https://github.com/Infqq/simpledemotivators/archive/main.zip --upgrade
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/Infqq/simpledemotivators/archive/main.zip
  Using cached https://github.com/Infqq/simpledemotivators/archive/main.zip
  Preparing metadata (setup.py) ... done
Collecting pillow==9.1.0
  Using cached Pillow-9.1.0.tar.gz (49.8 MB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.25.1->simpledemotivators==2.1.1) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.25.1->simpledemotivators==2.1.1) (2022.9.24)
Building wheels for collected packages: simpledemotivators, pillow
  Building wheel for simpledemotivators (setup.py) ... done
  Created wheel for simpledemotivators: filename=simpledemotivators-2.1.1-py3-none-any.whl size=4420 sha256=9c71b2b93e35a081edb302e2b3f624651aa9fde9c468ba04e8c135890cf800ef
  Stored in directory: /tmp/pip-ephem-wheel-cache-hb31g_7_/wheels/d4/8c/d9/b4ae328d512d0d9612efb1002a8d3df73601228ee95dc92c4e
  Building wheel for pillow (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [190 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Successfully built simpledemotivators
Failed to build pillow
Installing collected packages: pillow, idna, chardet, requests, simpledemotivators
  Running setup.py install for pillow ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pillow did not run successfully.
  │ exit code: 1
  ╰─> [195 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-cpython-311/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
          _build_ext.build_ext.run(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: jpeg
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-wj7fmda8/pillow_a004cd11cf2e4bd4b9eeea49217125a3/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
      
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by BUTERBROT1** [comment]
Насколько я понял ,демотиватор не работает потому что pillow не правильно установлен.Но я уже обновил pillow но ничего не поменялось

**Comment by MrBonjur** [comment]
НЕ ПОДДЕРЖИВАЕТСЯ Python 3.10
Pillow не работает на python 3.10+ и выше, при установке simpledemotivators так же устанавливается Pillow, и из-за него не работает. Нужно использовать Python 3.9 например

**Comment by dest4590** [comment]
> НЕ ПОДДЕРЖИВАЕТСЯ Python 3.10 Pillow не работает на python 3.10+ и выше, при установке simpledemotivators так же устанавливается Pillow, и из-за него не работает. Нужно использовать Python 3.9 например

кстати была такая-же ошибка, решилось переустановкой python с 3.12 на 3.8.10
