### ISSUE TITLE
По поводу последнего обновления

### ISSUE THREAD

**Issue by Ron788** [Infqq/simpledemotivators#9]
Мне непонятен смысл класса "text_gen", библиотека создана для генерации демотиваторов, но это лишнее, повторюсь по-моему

**Comment by Ron788** [comment]
Хочется заметить, этот класс стоило бы переименовать в "textgen", чтобы название всех классов было одного формата

**Comment by Infqq** [comment]
По сути данная функция нужна для рандомного текста в демотиваторах, но если мешает, то впринципе можно убрать.

**Comment by Ron788** [comment]
Случайный текст для демотиваторов, по моему, не нужен. Тому кому она может понадобиться, напишет сам

**Comment by Ron788** [comment]
Тем более, по моему лишним является генератор цитат великих людей. Тогда название библиотеке "simpledemotivators" немного не подходит, скорее "simpleMemesGenerator"

**Comment by Infqq** [comment]
Изменения названия библиотеки навряд ли будет, но как вариант можно перенести данные функции в новую библиотеку.

**Comment by Infqq** [comment]
Переношу в дискуссии.

**Comment by Nikoscocos** [comment]
Помогите, пожалуйста

**Comment by Nikoscocos** [comment]
проблема такая, опубликовал своего бота вк который генерирует демотиваторы 
залил я его на Heroku но тут такая проблема
![image](https://user-images.githubusercontent.com/77122703/115151868-d5038300-a07f-11eb-8a8e-b2bce7eaf2b5.png)
но у меня на пк всё работало!
прекрасная либа, очень полезная, но почему не работает на хостинге?

**Comment by Infqq** [comment]
> проблема такая, опубликовал своего бота вк который генерирует демотиваторы
> залил я его на Heroku но тут такая проблема
> ![image](https://user-images.githubusercontent.com/77122703/115151868-d5038300-a07f-11eb-8a8e-b2bce7eaf2b5.png)
> но у меня на пк всё работало!
> прекрасная либа, очень полезная, но почему не работает на хостинге?

Ознакомьтесь с новой документацией/создайте новый ишью, а не оффтопьте в этот

**Comment by Nikoscocos** [comment]
извините я не знаю насчёт гитхаб я тут недавно
а там что то поменялось в новой документации?

**Comment by Infqq** [comment]
> извините я не знаю насчёт гитхаб я тут недавно
> а там что то поменялось в новой документации?

Отпишите мне в телеграм: @infjq

**Comment by Nikoscocos** [comment]
спасибо, я разобрался
пользуясь случаем хочу сказать, ваша либа очень крутая

**Comment by Infqq** [comment]
> спасибо, я разобрался
> пользуясь случаем хочу сказать, ваша либа очень крутая

Спасибо! Если не сложно, то можете поставить стар (кнопка сверху)

**Comment by Ron788** [comment]
Установлена версия библиотеки >= 2.0.0, где классы переименнованы 2 решения:
1. Устанавливать библиотеку с pypi с версией 1.6.0 (по моему это последняя со старым синтаксисом)
2. Вручную переименовать классы, на новые названия

**Comment by Infqq** [comment]
Данная функция удалена
